apiVersion : apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app : app1
spec:
  selector:
    matchLabels:
      project: app1
  template:
    metadata:
      labels:
        project: app1
    spec:
      containers:
        - name : nginx-test
          image: nginx:latest
          ports:
            - containerPort: 80