apiVersion : apps/v1
kind: Deployment
metadata:
  name: second
  labels:
    app : second
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: second
  template:
    metadata:
      labels:
        project: second   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 8081

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: first
  labels:
    app : first
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: first
  template:
    metadata:
      labels:
        project: first   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : {{ .Release.Name }}-web1
          image: {{ .Values.container.image2 }}
          ports:
            - containerPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
      - name: testjob
        image: perl
        command: ["perl",  "-Mqweqwqwebignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
