apiVersion : apps/v1
kind: Deployment
metadata:
  name: SECOND
  labels:
    app : SECOND
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: SECOND
  template:
    metadata:
      labels:
        project: SECOND   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 8080

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: FIRST
  labels:
    app : FIRST
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: FIRST
  template:
    metadata:
      labels:
        project: FIRST   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : {{ .Release.Name }}-web1
          image: {{ .Values.container.image2 }}
          ports:
            - containerPort: 80